### ISSUE TITLE
Make External the default tab

### ISSUE THREAD

**Issue by svandragt** [hamishcampbell/silverstripe-auth-external#10]
Was wondering if the following change of defaults would be desirable:

When sites are using this plugin, I reckon that the majority of logins are going through the External login rather than the Email & Password (E&P) tab. The E&P tab on my sites are only really used for admin logins.

If this is the case, would it be desirable to make the External tab the one that is selected by default?

**Comment by hamishcampbell** [comment]
Yeah, I agree.

**Comment by svandragt** [comment]
Add the following line to _config.php to do this now before the fix is put in:

`Authenticator::set_default_authenticator('ExternalAuthenticator');`
